# coredns_setup.yml
- name: Instalar y configurar CoreDNS con Docker Compose en AlmaLinux 9
  hosts: infra-cluster
  become: true

  vars:
    coredns_version: "1.12.1"
    coredns_config_dir: "/etc/coredns"
    resolv_conf_path: "/etc/resolv.conf"
    domain_name: "socialdevs.site"
    api_vip: "192.168.0.32"
    ingress_vip: "192.168.0.33"

    nameservers:
      - "nameserver 10.17.3.11"
      - "nameserver 8.8.8.8"

    dns_records:
      - { name: "master1", ip: "10.17.4.21" }
      - { name: "master2", ip: "10.17.4.22" }
      - { name: "master3", ip: "10.17.4.23" }
      - { name: "worker1", ip: "10.17.4.24" }
      - { name: "worker2", ip: "10.17.4.25" }
      - { name: "worker3", ip: "10.17.4.26" }
      - { name: "storage1", ip: "10.17.4.27" }
      - { name: "infra-cluster", ip: "10.17.3.11" }
      - { name: "loadbalancer1", ip: "192.168.0.30" }
      - { name: "loadbalancer2", ip: "192.168.0.31" }
      - { name: "postgresql1", ip: "10.17.3.14" }

  tasks:
    - name: Instalar herramientas necesarias
      dnf:
        name:
          - curl
          - dnf-plugins-core
        state: present

    - name: Agregar repositorio oficial de Docker
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Instalar Docker y Docker Compose con --nobest
      shell: |
        dnf install --nobest -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
      args:
        chdir: /tmp

    - name: Habilitar e iniciar Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Crear directorio de configuración CoreDNS
      file:
        path: "{{ coredns_config_dir }}"
        state: directory
        mode: "0755"

    - name: Renderizar Corefile de CoreDNS
      template:
        src: templates/Corefile.j2
        dest: "{{ coredns_config_dir }}/Corefile"

    - name: Renderizar docker-compose.yml
      template:
        src: templates/coredns/docker-compose.yml.j2
        dest: "{{ coredns_config_dir }}/docker-compose.yml"

    - name: Iniciar CoreDNS con Docker Compose
      command: docker compose up -d
      args:
        chdir: "{{ coredns_config_dir }}"

    - name: Configurar resolv.conf
      copy:
        dest: "{{ resolv_conf_path }}"
        content: |
          {% for ns in nameservers %}
          {{ ns }}
          {% endfor %}